global:
  scrape_interval: 15s
scrape_configs:
  - job_name: bridge-api
    metrics_path: /metrics
    static_configs:
      - targets: ['api:4000']
  - job_name: nats
    metrics_path: /varz
    static_configs:
      - targets: ['nats:8222']
