import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./styles.css';
const API=import.meta.env.VITE_BRIDGE_API_URL||'http://localhost:4000';
function App(){const[tenants,setTenants]=useState([]),[tenant,setTenant]=useState(''),[apps,setApps]=useState([]),[resources,setResources]=useState([]),[audit,setAudit]=useState([]),[tab,setTab]=useState('apps'),[err,setErr]=useState('');
async function j(path,opt={}){const h={'content-type':'application/json',...(tenant?{'x-tenant-id':tenant}:{})};const r=await fetch(API+path,{...opt,headers:{...h,...opt.headers}});const x=await r.json();if(!r.ok)throw new Error(x.error||`HTTP ${r.status}`);return x}
useEffect(()=>{j('/api/tenants').then(x=>{setTenants(x);if(x[0])setTenant(x[0].id)}).catch(e=>setErr(e.message))},[]);useEffect(()=>{if(!tenant)return;Promise.all([j('/api/apps'),j('/api/resources'),j('/api/audit')]).then(([a,r,u])=>{setApps(a);setResources(r);setAudit(u);setErr('')}).catch(e=>setErr(e.message))},[tenant]);
async function act(id,action){try{await j(`/api/resources/${id}/lifecycle`,{method:'POST',body:JSON.stringify({action})});setResources(await j('/api/resources'))}catch(e){setErr(e.message)}}
return <div className="shell"><aside><h2>Bridge Control Center</h2>{['apps','resources','ai','growth','security','audit'].map(x=><button key={x} onClick={()=>setTab(x)}>{x}</button>)}</aside><main><header><div><h1>{tab.toUpperCase()}</h1><p>Multi-tenant SaaS ecosystem control plane</p></div><select value={tenant} onChange={e=>setTenant(e.target.value)}>{tenants.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></header>{err&&<div className="err">{err}</div>}{tab==='apps'&&<div className="cards">{apps.map(a=><article key={a.id}><span>{a.status}</span><h3>{a.name}</h3><p>{a.app_type} · {a.database_engine}</p><a href={a.launch_url} target="_blank">Launch</a></article>)}</div>}{tab==='resources'&&<table><thead><tr><th>Type</th><th>Name</th><th>State</th><th>Actions</th></tr></thead><tbody>{resources.map(r=><tr key={r.id}><td>{r.kind}</td><td>{r.name}</td><td>{r.state}</td><td>{r.availableActions.map(a=><button key={a} onClick={()=>act(r.id,a)}>{a}</button>)}</td></tr>)}</tbody></table>}{tab==='ai'&&<Ai tenant={tenant}/>} {tab==='growth'&&<Growth api={j}/>} {tab==='security'&&<Security api={j}/>} {tab==='audit'&&<table><thead><tr><th>Time</th><th>Action</th><th>Resource</th></tr></thead><tbody>{audit.map(x=><tr key={x.id}><td>{x.created_at}</td><td>{x.action}</td><td>{x.resource_type}</td></tr>)}</tbody></table>}</main></div>}
function Ai({tenant}){const[msgs,setMsgs]=useState([{role:'assistant',content:'Bridge AI Hub. Provider must be configured server-side.'}]),[text,setText]=useState(''),[err,setErr]=useState('');async function send(e){e.preventDefault();const q=text.trim();if(!q)return;const m=[...msgs,{role:'user',content:q}];setMsgs(m);setText('');const r=await fetch(API+'/api/ai/chat',{method:'POST',headers:{'content-type':'application/json','x-tenant-id':tenant},body:JSON.stringify({messages:m})});const j=await r.json();if(!r.ok){setErr(j.error);return}setMsgs(x=>[...x,{role:'assistant',content:j.content}])}return <section><div className="chat">{msgs.map((m,i)=><p key={i} className={m.role}><b>{m.role}</b><br/>{m.content}</p>)}</div>{err&&<div className="err">{err}</div>}<form onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask Bridge AI..."/><button>Send</button></form></section>}
function Growth({api}){const[rows,setRows]=useState([]);useEffect(()=>{api('/api/affiliates').then(setRows).catch(()=>{})},[]);return <section><h3>Affiliate Management</h3><table><thead><tr><th>Name</th><th>Email</th><th>Code</th><th>Rate</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.email}</td><td>{x.code}</td><td>{x.commission_rate}</td></tr>)}</tbody></table></section>}
function Security({api}){const[rows,setRows]=useState([]);useEffect(()=>{api('/api/security/rules').then(setRows).catch(()=>{})},[]);return <section><h3>Security / IP Rules</h3><table><thead><tr><th>Action</th><th>Target</th><th>Reason</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.action}</td><td>{x.target}</td><td>{x.reason}</td></tr>)}</tbody></table></section>}
createRoot(document.getElementById('root')).render(<App/>);
